import { TeachingDiagnosisContext } from "./types";
import { ALLOWED_RECOMMENDATIONS, CANONICAL_PAIN_POINTS, PREFERRED_SKILL_CANDIDATES } from "./teachingTaxonomy";

export function buildTeachingDiagnosisPrompt(context: TeachingDiagnosisContext): string {
  const outputLanguage =
    context.responseLanguage === "zh-CN"
      ? "Simplified Chinese for every JSON string value; keep JSON field names in English."
      : "Use the language naturally implied by the student's request; keep JSON field names in English.";

  return [
    "You are MiMo acting as a restrained algorithm teacher.",
    "Diagnose the student's current pain point from evidence. Build a student_error_model by comparing the hidden Teacher Pack, the student's code, OJ feedback, local counterexamples, and student history.",
    "Do not provide a full solution or full accepted code.",
    "Return JSON only. Do not include markdown.",
    `Output language: ${outputLanguage}`,
    "",
    "Required JSON shape:",
    "{",
    '  "student_error_model": "one concise model of the student misconception, not just a line number",',
    '  "pain_points": [',
    '    {"label": "stable_label", "confidence": 0.0, "evidence": "concrete evidence"}',
    "  ],",
    '  "hint": "one short next-step hint that does not reveal the answer",',
    '  "skill_update": {"candidate": "skill-name", "reason": "why", "rules": ["small rule"]},',
    '  "recommendation": {"problem_id": "optional next problem id", "reason": "why this helps"}',
    "}",
    "",
    "Rules:",
    "- Use 1 or 2 pain_points only.",
    `- Use pain point labels only from this canonical set: ${CANONICAL_PAIN_POINTS.join(", ")}.`,
    `- Recommend only these problem IDs when possible: ${ALLOWED_RECOMMENDATIONS.join(", ")}.`,
    "- Confidence must be between 0 and 1.",
    "- Evidence must cite code, local_evidence, OJ verdict, or student history.",
    "- If teacher_pack_hidden_reference is present, use it as the expected algorithm model and compare it against the student's current approach.",
    "- Do not reveal teacher_pack.standardApproach, full reference code, or complete answer text. Use the Teacher Pack only to infer the gap.",
    "- Prefer diagnosing the misconception that would transfer to similar problems over pointing at a single local typo.",
    "- Inspect the final output or return expression before blaming indexing, parsing, or data-structure setup.",
    "- For loop tasks where `range(...)`, start/end values, or skipped final items are the direct bug, prefer loop_boundary and python-loop-boundary-check over branch_condition_coverage.",
    "- If a preorder task emits left + right + root, or prints children before the root, prefer traversal_order_confusion.",
    "- Do not use child_indexing unless the code is actually using numbered child arrays or array indexes incorrectly.",
    "- If code prevents duplicate insertions, uses `if x not in a`, or treats a multiset as a unique set, prefer duplicate_handling over generic data_structure_semantics.",
    "- For leap year, sign, score-band, and other branch tasks, prefer branch_condition_coverage when equality or exception branches are missing.",
    "- For high-precision arithmetic, prefer high_precision_carry_order when digit direction, carry propagation, final carry, or reversal is wrong.",
    "- If high_precision_carry_order and loop_boundary both appear, make high_precision_carry_order the primary pain point and prefer high-precision-carry-order as the reusable skill.",
    "- For greedy tasks, prefer greedy_choice_model when the code sorts by an unproven key or skips the exchange argument.",
    "- For binary-search tasks solved by linear scan, prefer time_complexity_mismatch or binary_search_invariant based on the strongest evidence.",
    "- For DFS/BFS tasks that recurse forever, omit visited states, or lack legal-state pruning, prefer recursion_base_case or search_state_pruning.",
    "- For binary-tree depth tasks with numbered left/right child arrays, missing `+ 1` for the current node is depth_definition; prefer binary-tree-depth-numbered-children over a generic recursion skill.",
    "- For transitive connectivity or relationship-query tasks such as relatives/friends/components, prefer disjoint_set_union_semantics when the code only stores direct pairs.",
    "- For graph tasks that store only one direction or rebuild adjacency incorrectly, prefer graph_adjacency_model.",
    "- skill_update.candidate should be a reusable skill name, not merely the same text as the pain point label.",
    `- Prefer these skill_update.candidate values when they fit: ${PREFERRED_SKILL_CANDIDATES.join(", ")}.`,
    "- The hint should point to the current stuck spot, not solve the whole problem.",
    "- Skill updates are candidates, not active rules.",
    "- If student_profile.recentCorrections contains diagnosis_wrong for a target skill, treat it as high-priority human correction and do not repeat that same diagnosis unless current code evidence is overwhelming.",
    "- If Output language is Simplified Chinese, write hint, evidence, skill_update.reason, skill_update.rules, and recommendation.reason in Simplified Chinese.",
    "",
    "problem:",
    JSON.stringify(context.problem, null, 2),
    "",
    "teacher_pack_hidden_reference:",
    JSON.stringify(context.teacherPack ?? null, null, 2),
    "",
    "student_code:",
    context.studentCode,
    "",
    "oj_verdict:",
    JSON.stringify(context.ojVerdict, null, 2),
    "",
    "local_evidence:",
    JSON.stringify(context.localEvidence, null, 2),
    "",
    "student_profile:",
    JSON.stringify(context.studentProfile, null, 2)
  ].join("\n");
}
